---
# Check presence/create required Cinder volumes
- name: ensure presence of cinder volumes
  os_volume:
    state: present
    display_name: "{{ item.name }}"
    availability_zone: "{{ server_availability_zone }}"
    size: "{{ item.size | default(default_volume_size) }}"
    volume_type: "{{ item.type | default(omit) }}"
    metadata:
      "hw:passthrough": "true"
  loop: "{{ server_volumes }}"
  register: volumes_results

# Ensure, that AZ of the volume (if was existing) matches target
- assert:
    that: "{{ item.volume.availability_zone == server_availability_zone }}"
    msg: "Availability zone of the volume does not match target. Please destroy volumes"
  loop: "{{ volumes_results.results }}"
