---

cloud_name: otc
bms_name: bms-test
bms_image_name: Beta_OracleLinux_7UEK_BMS_latest
bms_flavor_name: physical.o2.medium
bms_networks:
  - net-id: 9d0afe15-fb4e-40b9-81b1-e37ed63b0793
bms_security_groups:

bms_availability_zone: eu-de-02
bms_key_name: KeyPair-e95e
