---
# Push Oracle installation SW to the server

- name: create oracle sw destination ({{ oracle_packages_location }})
  file:
    path: "{{ oracle_packages_location }}"
    state: directory
    mode: 0775

- name: unzip archive sw to configured remote destination
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: "{{ item.remote_src | default(omit) }}"
  loop: "{{ sw_packages_list | selectattr('type', 'defined') | selectattr('type', 'equalto', 'archive') | list }}"

- name: download sw to configured remote destination
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ sw_packages_list }}"
  when:
    - item.remote_src is defined and item.remote_src
    - item.type is not defined or item.type != 'archive'

- name: upload remaining sw from localhost to configured remote destination
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ sw_packages_list }}"
  when:
    - item.remote_src is not defined or not item.remote_src
    - item.type is not defined or item.type != 'archive'
