---

cloud_name: otc
server_name: matt-bms-rrs
server_networks:
  - net-id: 23289438-add4-4f9a-84ee-897691137180

# Security groups should be present
# server_security_groups:
  # - sg-Matt

server_availability_zone: eu-de-02
server_key_name: KeyPair-Matt-CM
# server_username: linux

# data volumes to attach/detach
server_volumes:
  - name: Matt-data-volume
  - name: Matt-data-volume1
  - name: Matt-data-volume2

# logical volume dict
lv:
  ora1:
    name: ora1
    vg: oradata
    mount: /oracle/ora1
  ora2:
    name: ora2
    vg: oradata
    mount: /oracle/ora2
  ora3:
    name: ora3
    vg: oradata
    mount: /oracle/ora3

# filesystem and mount options configuration
server_volumes_filesystem: xfs
server_volumes_mount_opt: rw
