---

cloud_name: otc
bms_name: matt-bms-rrs
bms_image_name: Beta_OracleLinux_7UEK_BMS_latest
bms_flavor_name: physical.o2.medium
bms_networks:
  - net-id: 23289438-add4-4f9a-84ee-897691137180

# Security groups should be present
bms_security_groups:
  - sg-Matt

bms_availability_zone: eu-de-02
bms_key_name: KeyPair-Matt-CM
bms_username: linux

# data volumes to attach/detach
default_volume_size: 10
bms_volumes:
  - name: Matt-data-volume
  - name: Matt-data-volume1
  - name: Matt-data-volume2

# logical volume dict
lv:
  ora1:
    name: ora1
    vg: oradata
    mount: /oracle/ora1
  ora2:
    name: ora2
    vg: oradata
    mount: /oracle/ora2
  ora3:
    name: ora3
    vg: oradata
    mount: /oracle/ora3

# filesystem and mount options configuration
bms_volumes_filesystem: xfs
bmx_volumes_mount_opt: rw
