---

cloud_name: otc
bms_name: matt-bms-rrs
bms_image_name: Beta_OracleLinux_7UEK_BMS_latest
bms_flavor_name: physical.o2.medium
bms_networks:
  - net-id: 23289438-add4-4f9a-84ee-897691137180

# Security groups should be present
bms_security_groups:
  - sg-Matt

bms_availability_zone: eu-de-02
bms_key_name: KeyPair-Matt-CM
bms_username: linux

# data volumes to attach/detach
bms_volumes:
  - Matt-data-volume
  - Matt-data-volume1
  - Matt-data-volume2


