---

- name: mount bms volumes
  mount:
    path: "{{ item.value.mount }}"
    src: /dev/{{ item.value.vg }}/{{ item.value.name }}
    fstype: "{{ server_volumes_filesystem }}"
    opts: "{{ server_volumes_mount_opt }}"
    state: mounted
  with_dict: "{{ lv }}"

